train_durations:
  value: ''
  unit: s
pulse_frequency:
  value: ''
  unit: Hz
interstimulus_interval:
  value: ''
  unit: s
pulse_period:
  value: ''
  unit: ms
outputs:
  alternatives:
    TTL: PulsePal used to send TTL
    Trigger: PulsePal used as trigger for electrical stimulation
    Sync: PulsePal used to synchronize
  value:
  - Trigger
  - ' Sync'
  definition: The output purpose.
start_times:
  value: ''
  unit: s
notes:
  value: ''
  definition: Notes specific for this stimulus session.
output_device:
  value: Pulse Pal
  definition: The physical output device.
outputs_to:
  value:
  - Intan Stimulation Recording Controller
  - ' Intan Stimulation Recording Controller'
  definition: The receiving end of the output channels.
output_channels:
  value:
  - 1.0
  - 4.0
  definition: The physical output channels used.
pulse_voltage:
  value: ''
  unit: Volt
pulse_phase_duration:
  value: ''
  unit: ms
definition: Describing the settings on pulse pal.
repetitions:
  value: ''
  definition: The number of repetitions of the described stimulation. Defined as on
    time of a train of pulses
name: alessio_pulse_pal_settings
pulse_sd:
  value: ''
  unit: '%'
trigger_software:
  alternatives:
    Matlab: Matlab software provided by PulsePal
    OpenEphys: Trigger software from the Open Ephys GUI
  value: ''
  definition: What software triggers the pulsepal.
identifier: alessio_pulse_pal_settings
trigger_channels:
  value: ''
  definition: If externally triggered, by which channel.
